/**
 * generated by Xtext 2.15.0
 */
package gui_proj.validation;

import gui_proj.validation.AbstractGUIValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GUIValidator extends AbstractGUIValidator {
}
