/*
 * generated by Xtext 2.15.0
 */
package gui_proj.ui;

import com.google.inject.Injector;
import gui_proj.ui.internal.Gui_projActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GUIExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Gui_projActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Gui_projActivator activator = Gui_projActivator.getInstance();
		return activator != null ? activator.getInjector(Gui_projActivator.GUI_PROJ_GUI) : null;
	}

}
