/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI.impl;

import gui_proj.gUI.Button;
import gui_proj.gUI.GUIElementDescription;
import gui_proj.gUI.GUIPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.impl.ButtonImpl#getButtonDescription <em>Button Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ButtonImpl extends GUIElementImpl implements Button
{
  /**
   * The cached value of the '{@link #getButtonDescription() <em>Button Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getButtonDescription()
   * @generated
   * @ordered
   */
  protected GUIElementDescription buttonDescription;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ButtonImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GUIPackage.Literals.BUTTON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GUIElementDescription getButtonDescription()
  {
    return buttonDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetButtonDescription(GUIElementDescription newButtonDescription, NotificationChain msgs)
  {
    GUIElementDescription oldButtonDescription = buttonDescription;
    buttonDescription = newButtonDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GUIPackage.BUTTON__BUTTON_DESCRIPTION, oldButtonDescription, newButtonDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setButtonDescription(GUIElementDescription newButtonDescription)
  {
    if (newButtonDescription != buttonDescription)
    {
      NotificationChain msgs = null;
      if (buttonDescription != null)
        msgs = ((InternalEObject)buttonDescription).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GUIPackage.BUTTON__BUTTON_DESCRIPTION, null, msgs);
      if (newButtonDescription != null)
        msgs = ((InternalEObject)newButtonDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GUIPackage.BUTTON__BUTTON_DESCRIPTION, null, msgs);
      msgs = basicSetButtonDescription(newButtonDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.BUTTON__BUTTON_DESCRIPTION, newButtonDescription, newButtonDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GUIPackage.BUTTON__BUTTON_DESCRIPTION:
        return basicSetButtonDescription(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GUIPackage.BUTTON__BUTTON_DESCRIPTION:
        return getButtonDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GUIPackage.BUTTON__BUTTON_DESCRIPTION:
        setButtonDescription((GUIElementDescription)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.BUTTON__BUTTON_DESCRIPTION:
        setButtonDescription((GUIElementDescription)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.BUTTON__BUTTON_DESCRIPTION:
        return buttonDescription != null;
    }
    return super.eIsSet(featureID);
  }

} //ButtonImpl
