/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI.impl;

import gui_proj.gUI.CheckBox;
import gui_proj.gUI.GUIElementDescription;
import gui_proj.gUI.GUIPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Check Box</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.impl.CheckBoxImpl#getCheckBoxDescription <em>Check Box Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CheckBoxImpl extends GUIElementImpl implements CheckBox
{
  /**
   * The cached value of the '{@link #getCheckBoxDescription() <em>Check Box Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCheckBoxDescription()
   * @generated
   * @ordered
   */
  protected GUIElementDescription checkBoxDescription;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CheckBoxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GUIPackage.Literals.CHECK_BOX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GUIElementDescription getCheckBoxDescription()
  {
    return checkBoxDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCheckBoxDescription(GUIElementDescription newCheckBoxDescription, NotificationChain msgs)
  {
    GUIElementDescription oldCheckBoxDescription = checkBoxDescription;
    checkBoxDescription = newCheckBoxDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION, oldCheckBoxDescription, newCheckBoxDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCheckBoxDescription(GUIElementDescription newCheckBoxDescription)
  {
    if (newCheckBoxDescription != checkBoxDescription)
    {
      NotificationChain msgs = null;
      if (checkBoxDescription != null)
        msgs = ((InternalEObject)checkBoxDescription).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION, null, msgs);
      if (newCheckBoxDescription != null)
        msgs = ((InternalEObject)newCheckBoxDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION, null, msgs);
      msgs = basicSetCheckBoxDescription(newCheckBoxDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION, newCheckBoxDescription, newCheckBoxDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION:
        return basicSetCheckBoxDescription(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION:
        return getCheckBoxDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION:
        setCheckBoxDescription((GUIElementDescription)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION:
        setCheckBoxDescription((GUIElementDescription)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.CHECK_BOX__CHECK_BOX_DESCRIPTION:
        return checkBoxDescription != null;
    }
    return super.eIsSet(featureID);
  }

} //CheckBoxImpl
