/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI.impl;

import gui_proj.gUI.GUIElementDescription;
import gui_proj.gUI.GUIPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element Description</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.impl.GUIElementDescriptionImpl#getCallback <em>Callback</em>}</li>
 *   <li>{@link gui_proj.gUI.impl.GUIElementDescriptionImpl#getText <em>Text</em>}</li>
 *   <li>{@link gui_proj.gUI.impl.GUIElementDescriptionImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link gui_proj.gUI.impl.GUIElementDescriptionImpl#getTop <em>Top</em>}</li>
 *   <li>{@link gui_proj.gUI.impl.GUIElementDescriptionImpl#getHeigth <em>Heigth</em>}</li>
 *   <li>{@link gui_proj.gUI.impl.GUIElementDescriptionImpl#getWidth <em>Width</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GUIElementDescriptionImpl extends MinimalEObjectImpl.Container implements GUIElementDescription
{
  /**
   * The default value of the '{@link #getCallback() <em>Callback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCallback()
   * @generated
   * @ordered
   */
  protected static final String CALLBACK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCallback() <em>Callback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCallback()
   * @generated
   * @ordered
   */
  protected String callback = CALLBACK_EDEFAULT;

  /**
   * The default value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected static final String TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getText() <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getText()
   * @generated
   * @ordered
   */
  protected String text = TEXT_EDEFAULT;

  /**
   * The default value of the '{@link #getLeft() <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected static final int LEFT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected int left = LEFT_EDEFAULT;

  /**
   * The default value of the '{@link #getTop() <em>Top</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTop()
   * @generated
   * @ordered
   */
  protected static final int TOP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTop() <em>Top</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTop()
   * @generated
   * @ordered
   */
  protected int top = TOP_EDEFAULT;

  /**
   * The default value of the '{@link #getHeigth() <em>Heigth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHeigth()
   * @generated
   * @ordered
   */
  protected static final int HEIGTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHeigth() <em>Heigth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHeigth()
   * @generated
   * @ordered
   */
  protected int heigth = HEIGTH_EDEFAULT;

  /**
   * The default value of the '{@link #getWidth() <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected static final int WIDTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getWidth() <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWidth()
   * @generated
   * @ordered
   */
  protected int width = WIDTH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GUIElementDescriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GUIPackage.Literals.GUI_ELEMENT_DESCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCallback()
  {
    return callback;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCallback(String newCallback)
  {
    String oldCallback = callback;
    callback = newCallback;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.GUI_ELEMENT_DESCRIPTION__CALLBACK, oldCallback, callback));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getText()
  {
    return text;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setText(String newText)
  {
    String oldText = text;
    text = newText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.GUI_ELEMENT_DESCRIPTION__TEXT, oldText, text));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getLeft()
  {
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLeft(int newLeft)
  {
    int oldLeft = left;
    left = newLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.GUI_ELEMENT_DESCRIPTION__LEFT, oldLeft, left));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTop()
  {
    return top;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTop(int newTop)
  {
    int oldTop = top;
    top = newTop;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.GUI_ELEMENT_DESCRIPTION__TOP, oldTop, top));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getHeigth()
  {
    return heigth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHeigth(int newHeigth)
  {
    int oldHeigth = heigth;
    heigth = newHeigth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.GUI_ELEMENT_DESCRIPTION__HEIGTH, oldHeigth, heigth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getWidth()
  {
    return width;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWidth(int newWidth)
  {
    int oldWidth = width;
    width = newWidth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.GUI_ELEMENT_DESCRIPTION__WIDTH, oldWidth, width));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__CALLBACK:
        return getCallback();
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TEXT:
        return getText();
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__LEFT:
        return getLeft();
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TOP:
        return getTop();
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__HEIGTH:
        return getHeigth();
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__WIDTH:
        return getWidth();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__CALLBACK:
        setCallback((String)newValue);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TEXT:
        setText((String)newValue);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__LEFT:
        setLeft((Integer)newValue);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TOP:
        setTop((Integer)newValue);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__HEIGTH:
        setHeigth((Integer)newValue);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__WIDTH:
        setWidth((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__CALLBACK:
        setCallback(CALLBACK_EDEFAULT);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TEXT:
        setText(TEXT_EDEFAULT);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__LEFT:
        setLeft(LEFT_EDEFAULT);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TOP:
        setTop(TOP_EDEFAULT);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__HEIGTH:
        setHeigth(HEIGTH_EDEFAULT);
        return;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__WIDTH:
        setWidth(WIDTH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__CALLBACK:
        return CALLBACK_EDEFAULT == null ? callback != null : !CALLBACK_EDEFAULT.equals(callback);
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TEXT:
        return TEXT_EDEFAULT == null ? text != null : !TEXT_EDEFAULT.equals(text);
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__LEFT:
        return left != LEFT_EDEFAULT;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__TOP:
        return top != TOP_EDEFAULT;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__HEIGTH:
        return heigth != HEIGTH_EDEFAULT;
      case GUIPackage.GUI_ELEMENT_DESCRIPTION__WIDTH:
        return width != WIDTH_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (callback: ");
    result.append(callback);
    result.append(", text: ");
    result.append(text);
    result.append(", left: ");
    result.append(left);
    result.append(", top: ");
    result.append(top);
    result.append(", heigth: ");
    result.append(heigth);
    result.append(", width: ");
    result.append(width);
    result.append(')');
    return result.toString();
  }

} //GUIElementDescriptionImpl
