/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI.impl;

import gui_proj.gUI.Button;
import gui_proj.gUI.CheckBox;
import gui_proj.gUI.GUIElement;
import gui_proj.gUI.GUIElementDescription;
import gui_proj.gUI.GUIFactory;
import gui_proj.gUI.GUIPackage;
import gui_proj.gUI.Gui;
import gui_proj.gUI.InputField;
import gui_proj.gUI.RadioButton;
import gui_proj.gUI.TextLabel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GUIPackageImpl extends EPackageImpl implements GUIPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass guiEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass guiElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass guiElementDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass textLabelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inputFieldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass buttonEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass radioButtonEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass checkBoxEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see gui_proj.gUI.GUIPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private GUIPackageImpl()
  {
    super(eNS_URI, GUIFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link GUIPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static GUIPackage init()
  {
    if (isInited) return (GUIPackage)EPackage.Registry.INSTANCE.getEPackage(GUIPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredGUIPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    GUIPackageImpl theGUIPackage = registeredGUIPackage instanceof GUIPackageImpl ? (GUIPackageImpl)registeredGUIPackage : new GUIPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theGUIPackage.createPackageContents();

    // Initialize created meta-data
    theGUIPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theGUIPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(GUIPackage.eNS_URI, theGUIPackage);
    return theGUIPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGui()
  {
    return guiEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGui_Name()
  {
    return (EAttribute)guiEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGui_Titel()
  {
    return (EAttribute)guiEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGui_Height()
  {
    return (EAttribute)guiEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGui_Width()
  {
    return (EAttribute)guiEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGui_GuiObjects()
  {
    return (EReference)guiEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGUIElement()
  {
    return guiElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElement_Name()
  {
    return (EAttribute)guiElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGUIElementDescription()
  {
    return guiElementDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElementDescription_Callback()
  {
    return (EAttribute)guiElementDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElementDescription_Text()
  {
    return (EAttribute)guiElementDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElementDescription_Left()
  {
    return (EAttribute)guiElementDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElementDescription_Top()
  {
    return (EAttribute)guiElementDescriptionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElementDescription_Heigth()
  {
    return (EAttribute)guiElementDescriptionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGUIElementDescription_Width()
  {
    return (EAttribute)guiElementDescriptionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTextLabel()
  {
    return textLabelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTextLabel_TextLabelDescription()
  {
    return (EReference)textLabelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInputField()
  {
    return inputFieldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInputField_InputFieldDescription()
  {
    return (EReference)inputFieldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getButton()
  {
    return buttonEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getButton_ButtonDescription()
  {
    return (EReference)buttonEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRadioButton()
  {
    return radioButtonEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRadioButton_RadioButtonDescription()
  {
    return (EReference)radioButtonEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCheckBox()
  {
    return checkBoxEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCheckBox_CheckBoxDescription()
  {
    return (EReference)checkBoxEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GUIFactory getGUIFactory()
  {
    return (GUIFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    guiEClass = createEClass(GUI);
    createEAttribute(guiEClass, GUI__NAME);
    createEAttribute(guiEClass, GUI__TITEL);
    createEAttribute(guiEClass, GUI__HEIGHT);
    createEAttribute(guiEClass, GUI__WIDTH);
    createEReference(guiEClass, GUI__GUI_OBJECTS);

    guiElementEClass = createEClass(GUI_ELEMENT);
    createEAttribute(guiElementEClass, GUI_ELEMENT__NAME);

    guiElementDescriptionEClass = createEClass(GUI_ELEMENT_DESCRIPTION);
    createEAttribute(guiElementDescriptionEClass, GUI_ELEMENT_DESCRIPTION__CALLBACK);
    createEAttribute(guiElementDescriptionEClass, GUI_ELEMENT_DESCRIPTION__TEXT);
    createEAttribute(guiElementDescriptionEClass, GUI_ELEMENT_DESCRIPTION__LEFT);
    createEAttribute(guiElementDescriptionEClass, GUI_ELEMENT_DESCRIPTION__TOP);
    createEAttribute(guiElementDescriptionEClass, GUI_ELEMENT_DESCRIPTION__HEIGTH);
    createEAttribute(guiElementDescriptionEClass, GUI_ELEMENT_DESCRIPTION__WIDTH);

    textLabelEClass = createEClass(TEXT_LABEL);
    createEReference(textLabelEClass, TEXT_LABEL__TEXT_LABEL_DESCRIPTION);

    inputFieldEClass = createEClass(INPUT_FIELD);
    createEReference(inputFieldEClass, INPUT_FIELD__INPUT_FIELD_DESCRIPTION);

    buttonEClass = createEClass(BUTTON);
    createEReference(buttonEClass, BUTTON__BUTTON_DESCRIPTION);

    radioButtonEClass = createEClass(RADIO_BUTTON);
    createEReference(radioButtonEClass, RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION);

    checkBoxEClass = createEClass(CHECK_BOX);
    createEReference(checkBoxEClass, CHECK_BOX__CHECK_BOX_DESCRIPTION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    textLabelEClass.getESuperTypes().add(this.getGUIElement());
    inputFieldEClass.getESuperTypes().add(this.getGUIElement());
    buttonEClass.getESuperTypes().add(this.getGUIElement());
    radioButtonEClass.getESuperTypes().add(this.getGUIElement());
    checkBoxEClass.getESuperTypes().add(this.getGUIElement());

    // Initialize classes and features; add operations and parameters
    initEClass(guiEClass, Gui.class, "Gui", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGui_Name(), ecorePackage.getEString(), "name", null, 0, 1, Gui.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGui_Titel(), ecorePackage.getEString(), "titel", null, 0, 1, Gui.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGui_Height(), ecorePackage.getEInt(), "height", null, 0, 1, Gui.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGui_Width(), ecorePackage.getEInt(), "width", null, 0, 1, Gui.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGui_GuiObjects(), this.getGUIElement(), null, "guiObjects", null, 0, -1, Gui.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(guiElementEClass, GUIElement.class, "GUIElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGUIElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, GUIElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(guiElementDescriptionEClass, GUIElementDescription.class, "GUIElementDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGUIElementDescription_Callback(), ecorePackage.getEString(), "callback", null, 0, 1, GUIElementDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGUIElementDescription_Text(), ecorePackage.getEString(), "text", null, 0, 1, GUIElementDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGUIElementDescription_Left(), ecorePackage.getEInt(), "left", null, 0, 1, GUIElementDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGUIElementDescription_Top(), ecorePackage.getEInt(), "top", null, 0, 1, GUIElementDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGUIElementDescription_Heigth(), ecorePackage.getEInt(), "heigth", null, 0, 1, GUIElementDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGUIElementDescription_Width(), ecorePackage.getEInt(), "width", null, 0, 1, GUIElementDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(textLabelEClass, TextLabel.class, "TextLabel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTextLabel_TextLabelDescription(), this.getGUIElementDescription(), null, "textLabelDescription", null, 0, 1, TextLabel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(inputFieldEClass, InputField.class, "InputField", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInputField_InputFieldDescription(), this.getGUIElementDescription(), null, "inputFieldDescription", null, 0, 1, InputField.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(buttonEClass, Button.class, "Button", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getButton_ButtonDescription(), this.getGUIElementDescription(), null, "buttonDescription", null, 0, 1, Button.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(radioButtonEClass, RadioButton.class, "RadioButton", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRadioButton_RadioButtonDescription(), this.getGUIElementDescription(), null, "radioButtonDescription", null, 0, 1, RadioButton.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(checkBoxEClass, CheckBox.class, "CheckBox", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCheckBox_CheckBoxDescription(), this.getGUIElementDescription(), null, "checkBoxDescription", null, 0, 1, CheckBox.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //GUIPackageImpl
