/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI.impl;

import gui_proj.gUI.GUIElementDescription;
import gui_proj.gUI.GUIPackage;
import gui_proj.gUI.RadioButton;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Radio Button</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.impl.RadioButtonImpl#getRadioButtonDescription <em>Radio Button Description</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RadioButtonImpl extends GUIElementImpl implements RadioButton
{
  /**
   * The cached value of the '{@link #getRadioButtonDescription() <em>Radio Button Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRadioButtonDescription()
   * @generated
   * @ordered
   */
  protected GUIElementDescription radioButtonDescription;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RadioButtonImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GUIPackage.Literals.RADIO_BUTTON;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GUIElementDescription getRadioButtonDescription()
  {
    return radioButtonDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRadioButtonDescription(GUIElementDescription newRadioButtonDescription, NotificationChain msgs)
  {
    GUIElementDescription oldRadioButtonDescription = radioButtonDescription;
    radioButtonDescription = newRadioButtonDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION, oldRadioButtonDescription, newRadioButtonDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRadioButtonDescription(GUIElementDescription newRadioButtonDescription)
  {
    if (newRadioButtonDescription != radioButtonDescription)
    {
      NotificationChain msgs = null;
      if (radioButtonDescription != null)
        msgs = ((InternalEObject)radioButtonDescription).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION, null, msgs);
      if (newRadioButtonDescription != null)
        msgs = ((InternalEObject)newRadioButtonDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION, null, msgs);
      msgs = basicSetRadioButtonDescription(newRadioButtonDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION, newRadioButtonDescription, newRadioButtonDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION:
        return basicSetRadioButtonDescription(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION:
        return getRadioButtonDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION:
        setRadioButtonDescription((GUIElementDescription)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION:
        setRadioButtonDescription((GUIElementDescription)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GUIPackage.RADIO_BUTTON__RADIO_BUTTON_DESCRIPTION:
        return radioButtonDescription != null;
    }
    return super.eIsSet(featureID);
  }

} //RadioButtonImpl
