/**
 * generated by Xtext 2.15.0
 */
package gui_proj.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gui_proj.GUIRuntimeModule;
import gui_proj.GUIStandaloneSetup;
import gui_proj.ide.GUIIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GUIIdeSetup extends GUIStandaloneSetup {
  @Override
  public Injector createInjector() {
    GUIRuntimeModule _gUIRuntimeModule = new GUIRuntimeModule();
    GUIIdeModule _gUIIdeModule = new GUIIdeModule();
    return Guice.createInjector(Modules2.mixin(_gUIRuntimeModule, _gUIIdeModule));
  }
}
