/**
 * generated by Xtext 2.15.0
 */
package gui_proj.ide;

import gui_proj.ide.AbstractGUIIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GUIIdeModule extends AbstractGUIIdeModule {
}
