/**
 * generated by Xtext 2.15.0
 */
package gui_proj.scoping;

import gui_proj.scoping.AbstractGUIScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GUIScopeProvider extends AbstractGUIScopeProvider {
}
