/**
 * generated by Xtext 2.15.0
 */
package gui_proj.ui;

import gui_proj.ui.AbstractGUIUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GUIUiModule extends AbstractGUIUiModule {
  public GUIUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
