/*
 * generated by Xtext 2.15.0
 */
package gui_proj.ide

import com.google.inject.Guice
import gui_proj.GUIRuntimeModule
import gui_proj.GUIStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GUIIdeSetup extends GUIStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GUIRuntimeModule, new GUIIdeModule))
	}
	
}
