/*
 * generated by Xtext 2.15.0
 */
package gui_proj.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import gui_proj.ide.contentassist.antlr.internal.InternalGUIParser;
import gui_proj.services.GUIGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GUIParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GUIGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GUIGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getGUIElementAccess().getAlternatives(), "rule__GUIElement__Alternatives");
			builder.put(grammarAccess.getGuiAccess().getGroup(), "rule__Gui__Group__0");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getGroup(), "rule__GUIElementDescription__Group__0");
			builder.put(grammarAccess.getTextLabelAccess().getGroup(), "rule__TextLabel__Group__0");
			builder.put(grammarAccess.getInputFieldAccess().getGroup(), "rule__InputField__Group__0");
			builder.put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
			builder.put(grammarAccess.getRadioButtonAccess().getGroup(), "rule__RadioButton__Group__0");
			builder.put(grammarAccess.getCheckBoxAccess().getGroup(), "rule__CheckBox__Group__0");
			builder.put(grammarAccess.getGuiAccess().getNameAssignment_1(), "rule__Gui__NameAssignment_1");
			builder.put(grammarAccess.getGuiAccess().getTitelAssignment_3(), "rule__Gui__TitelAssignment_3");
			builder.put(grammarAccess.getGuiAccess().getHeightAssignment_5(), "rule__Gui__HeightAssignment_5");
			builder.put(grammarAccess.getGuiAccess().getWidthAssignment_7(), "rule__Gui__WidthAssignment_7");
			builder.put(grammarAccess.getGuiAccess().getGuiObjectsAssignment_8(), "rule__Gui__GuiObjectsAssignment_8");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getCallbackAssignment_1(), "rule__GUIElementDescription__CallbackAssignment_1");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getTextAssignment_3(), "rule__GUIElementDescription__TextAssignment_3");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getLeftAssignment_5(), "rule__GUIElementDescription__LeftAssignment_5");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getTopAssignment_7(), "rule__GUIElementDescription__TopAssignment_7");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getHeigthAssignment_9(), "rule__GUIElementDescription__HeigthAssignment_9");
			builder.put(grammarAccess.getGUIElementDescriptionAccess().getWidthAssignment_11(), "rule__GUIElementDescription__WidthAssignment_11");
			builder.put(grammarAccess.getTextLabelAccess().getNameAssignment_1(), "rule__TextLabel__NameAssignment_1");
			builder.put(grammarAccess.getTextLabelAccess().getTextLabelDescriptionAssignment_3(), "rule__TextLabel__TextLabelDescriptionAssignment_3");
			builder.put(grammarAccess.getInputFieldAccess().getNameAssignment_1(), "rule__InputField__NameAssignment_1");
			builder.put(grammarAccess.getInputFieldAccess().getInputFieldDescriptionAssignment_3(), "rule__InputField__InputFieldDescriptionAssignment_3");
			builder.put(grammarAccess.getButtonAccess().getNameAssignment_1(), "rule__Button__NameAssignment_1");
			builder.put(grammarAccess.getButtonAccess().getButtonDescriptionAssignment_3(), "rule__Button__ButtonDescriptionAssignment_3");
			builder.put(grammarAccess.getRadioButtonAccess().getNameAssignment_1(), "rule__RadioButton__NameAssignment_1");
			builder.put(grammarAccess.getRadioButtonAccess().getRadioButtonDescriptionAssignment_3(), "rule__RadioButton__RadioButtonDescriptionAssignment_3");
			builder.put(grammarAccess.getCheckBoxAccess().getNameAssignment_1(), "rule__CheckBox__NameAssignment_1");
			builder.put(grammarAccess.getCheckBoxAccess().getCheckBoxDescriptionAssignment_3(), "rule__CheckBox__CheckBoxDescriptionAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GUIGrammarAccess grammarAccess;

	@Override
	protected InternalGUIParser createParser() {
		InternalGUIParser result = new InternalGUIParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GUIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GUIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
