/**
 * generated by Xtext 2.15.0
 */
package gui_proj;

import gui_proj.AbstractGUIRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GUIRuntimeModule extends AbstractGUIRuntimeModule {
}
