/**
 * generated by Xtext 2.15.0
 */
package gui_proj;

import gui_proj.GUIStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GUIStandaloneSetup extends GUIStandaloneSetupGenerated {
  public static void doSetup() {
    new GUIStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
