/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.Button#getButtonDescription <em>Button Description</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getButton()
 * @model
 * @generated
 */
public interface Button extends GUIElement
{
  /**
   * Returns the value of the '<em><b>Button Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Button Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Button Description</em>' containment reference.
   * @see #setButtonDescription(GUIElementDescription)
   * @see gui_proj.gUI.GUIPackage#getButton_ButtonDescription()
   * @model containment="true"
   * @generated
   */
  GUIElementDescription getButtonDescription();

  /**
   * Sets the value of the '{@link gui_proj.gUI.Button#getButtonDescription <em>Button Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Button Description</em>' containment reference.
   * @see #getButtonDescription()
   * @generated
   */
  void setButtonDescription(GUIElementDescription value);

} // Button
