/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check Box</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.CheckBox#getCheckBoxDescription <em>Check Box Description</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getCheckBox()
 * @model
 * @generated
 */
public interface CheckBox extends GUIElement
{
  /**
   * Returns the value of the '<em><b>Check Box Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Check Box Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Check Box Description</em>' containment reference.
   * @see #setCheckBoxDescription(GUIElementDescription)
   * @see gui_proj.gUI.GUIPackage#getCheckBox_CheckBoxDescription()
   * @model containment="true"
   * @generated
   */
  GUIElementDescription getCheckBoxDescription();

  /**
   * Sets the value of the '{@link gui_proj.gUI.CheckBox#getCheckBoxDescription <em>Check Box Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Check Box Description</em>' containment reference.
   * @see #getCheckBoxDescription()
   * @generated
   */
  void setCheckBoxDescription(GUIElementDescription value);

} // CheckBox
