/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gui</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.Gui#getName <em>Name</em>}</li>
 *   <li>{@link gui_proj.gUI.Gui#getTitel <em>Titel</em>}</li>
 *   <li>{@link gui_proj.gUI.Gui#getHeight <em>Height</em>}</li>
 *   <li>{@link gui_proj.gUI.Gui#getWidth <em>Width</em>}</li>
 *   <li>{@link gui_proj.gUI.Gui#getGuiObjects <em>Gui Objects</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getGui()
 * @model
 * @generated
 */
public interface Gui extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see gui_proj.gUI.GUIPackage#getGui_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link gui_proj.gUI.Gui#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Titel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titel</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titel</em>' attribute.
   * @see #setTitel(String)
   * @see gui_proj.gUI.GUIPackage#getGui_Titel()
   * @model
   * @generated
   */
  String getTitel();

  /**
   * Sets the value of the '{@link gui_proj.gUI.Gui#getTitel <em>Titel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titel</em>' attribute.
   * @see #getTitel()
   * @generated
   */
  void setTitel(String value);

  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Height</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(int)
   * @see gui_proj.gUI.GUIPackage#getGui_Height()
   * @model
   * @generated
   */
  int getHeight();

  /**
   * Sets the value of the '{@link gui_proj.gUI.Gui#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(int value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see gui_proj.gUI.GUIPackage#getGui_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link gui_proj.gUI.Gui#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

  /**
   * Returns the value of the '<em><b>Gui Objects</b></em>' containment reference list.
   * The list contents are of type {@link gui_proj.gUI.GUIElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gui Objects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gui Objects</em>' containment reference list.
   * @see gui_proj.gUI.GUIPackage#getGui_GuiObjects()
   * @model containment="true"
   * @generated
   */
  EList<GUIElement> getGuiObjects();

} // Gui
