/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.GUIElementDescription#getCallback <em>Callback</em>}</li>
 *   <li>{@link gui_proj.gUI.GUIElementDescription#getText <em>Text</em>}</li>
 *   <li>{@link gui_proj.gUI.GUIElementDescription#getLeft <em>Left</em>}</li>
 *   <li>{@link gui_proj.gUI.GUIElementDescription#getTop <em>Top</em>}</li>
 *   <li>{@link gui_proj.gUI.GUIElementDescription#getHeigth <em>Heigth</em>}</li>
 *   <li>{@link gui_proj.gUI.GUIElementDescription#getWidth <em>Width</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getGUIElementDescription()
 * @model
 * @generated
 */
public interface GUIElementDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Callback</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Callback</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Callback</em>' attribute.
   * @see #setCallback(String)
   * @see gui_proj.gUI.GUIPackage#getGUIElementDescription_Callback()
   * @model
   * @generated
   */
  String getCallback();

  /**
   * Sets the value of the '{@link gui_proj.gUI.GUIElementDescription#getCallback <em>Callback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Callback</em>' attribute.
   * @see #getCallback()
   * @generated
   */
  void setCallback(String value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see gui_proj.gUI.GUIPackage#getGUIElementDescription_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link gui_proj.gUI.GUIElementDescription#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(int)
   * @see gui_proj.gUI.GUIPackage#getGUIElementDescription_Left()
   * @model
   * @generated
   */
  int getLeft();

  /**
   * Sets the value of the '{@link gui_proj.gUI.GUIElementDescription#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(int value);

  /**
   * Returns the value of the '<em><b>Top</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Top</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top</em>' attribute.
   * @see #setTop(int)
   * @see gui_proj.gUI.GUIPackage#getGUIElementDescription_Top()
   * @model
   * @generated
   */
  int getTop();

  /**
   * Sets the value of the '{@link gui_proj.gUI.GUIElementDescription#getTop <em>Top</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top</em>' attribute.
   * @see #getTop()
   * @generated
   */
  void setTop(int value);

  /**
   * Returns the value of the '<em><b>Heigth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Heigth</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Heigth</em>' attribute.
   * @see #setHeigth(int)
   * @see gui_proj.gUI.GUIPackage#getGUIElementDescription_Heigth()
   * @model
   * @generated
   */
  int getHeigth();

  /**
   * Sets the value of the '{@link gui_proj.gUI.GUIElementDescription#getHeigth <em>Heigth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Heigth</em>' attribute.
   * @see #getHeigth()
   * @generated
   */
  void setHeigth(int value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Width</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see gui_proj.gUI.GUIPackage#getGUIElementDescription_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link gui_proj.gUI.GUIElementDescription#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

} // GUIElementDescription
