/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.InputField#getInputFieldDescription <em>Input Field Description</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getInputField()
 * @model
 * @generated
 */
public interface InputField extends GUIElement
{
  /**
   * Returns the value of the '<em><b>Input Field Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Input Field Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Field Description</em>' containment reference.
   * @see #setInputFieldDescription(GUIElementDescription)
   * @see gui_proj.gUI.GUIPackage#getInputField_InputFieldDescription()
   * @model containment="true"
   * @generated
   */
  GUIElementDescription getInputFieldDescription();

  /**
   * Sets the value of the '{@link gui_proj.gUI.InputField#getInputFieldDescription <em>Input Field Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Field Description</em>' containment reference.
   * @see #getInputFieldDescription()
   * @generated
   */
  void setInputFieldDescription(GUIElementDescription value);

} // InputField
