/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Radio Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.RadioButton#getRadioButtonDescription <em>Radio Button Description</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getRadioButton()
 * @model
 * @generated
 */
public interface RadioButton extends GUIElement
{
  /**
   * Returns the value of the '<em><b>Radio Button Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Radio Button Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Radio Button Description</em>' containment reference.
   * @see #setRadioButtonDescription(GUIElementDescription)
   * @see gui_proj.gUI.GUIPackage#getRadioButton_RadioButtonDescription()
   * @model containment="true"
   * @generated
   */
  GUIElementDescription getRadioButtonDescription();

  /**
   * Sets the value of the '{@link gui_proj.gUI.RadioButton#getRadioButtonDescription <em>Radio Button Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Radio Button Description</em>' containment reference.
   * @see #getRadioButtonDescription()
   * @generated
   */
  void setRadioButtonDescription(GUIElementDescription value);

} // RadioButton
