/**
 * generated by Xtext 2.15.0
 */
package gui_proj.gUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text Label</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gui_proj.gUI.TextLabel#getTextLabelDescription <em>Text Label Description</em>}</li>
 * </ul>
 *
 * @see gui_proj.gUI.GUIPackage#getTextLabel()
 * @model
 * @generated
 */
public interface TextLabel extends GUIElement
{
  /**
   * Returns the value of the '<em><b>Text Label Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text Label Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text Label Description</em>' containment reference.
   * @see #setTextLabelDescription(GUIElementDescription)
   * @see gui_proj.gUI.GUIPackage#getTextLabel_TextLabelDescription()
   * @model containment="true"
   * @generated
   */
  GUIElementDescription getTextLabelDescription();

  /**
   * Sets the value of the '{@link gui_proj.gUI.TextLabel#getTextLabelDescription <em>Text Label Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text Label Description</em>' containment reference.
   * @see #getTextLabelDescription()
   * @generated
   */
  void setTextLabelDescription(GUIElementDescription value);

} // TextLabel
