/**
 * generated by Xtext 2.15.0
 */
package gui_proj.ui.contentassist;

import gui_proj.ui.contentassist.AbstractGUIProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GUIProposalProvider extends AbstractGUIProposalProvider {
}
