/*
 * generated by Xtext 2.15.0
 */
package gui_proj.parser.antlr;

import com.google.inject.Inject;
import gui_proj.parser.antlr.internal.InternalGUIParser;
import gui_proj.services.GUIGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GUIParser extends AbstractAntlrParser {

	@Inject
	private GUIGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGUIParser createParser(XtextTokenStream stream) {
		return new InternalGUIParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Gui";
	}

	public GUIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GUIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
