/*
 * generated by Xtext 2.15.0
 */
package gui_proj.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGUIScopeProvider extends DelegatingScopeProvider {
}
