/*
 * generated by Xtext 2.15.0
 */
package gui_proj.ui.tests;

import com.google.inject.Injector;
import gui_proj.ui.internal.Gui_projActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GUIUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Gui_projActivator.getInstance().getInjector("gui_proj.GUI");
	}

}
