/**
 * generated by Xtext 2.15.0
 */
package gui_proj.tests;

import com.google.inject.Inject;
import gui_proj.tests.GUIInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(GUIInjectorProvider.class)
@SuppressWarnings("all")
public class GUIParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field GUIParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
